### ISSUE TITLE
Removing dependency on the .progress file

### ISSUE THREAD

**Issue by emsesc** [bitprj/counselor#20]
## Context
Currently, the .progress file dictates what step needs to run in the workflow files.
Example:
```yml
      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 1
        uses: cypress-io/github-action@v2
        if: ${{steps.vars.outputs.count == 38 && github.event.head_commit.message != 'Update progress'}}
        with:
          spec: cypress/integration/4.1.spec.js
```

## Problem
* Content in the .progress file can cause merge conflicts
* Isn't always updated when new branches are created
* Students to have to continually do git pull to pull commits from the bot.
* The bot code and workflow runs also have to catch the "update progress" commit and ignore it

## Solution
- [x] #27
- [x] #28
- [x] #29
- [ ] Use the count to determine which step to run

## References
* For querying Hasura, refer to the graphql calls in the counselor code. Note the authentication requirements
* Figure out a way to pass in the username, repoName into the javascript file. This could possibly be the bot storing repository secrets at the start of the camp
* For running files and storing output of commands in a secret to be used later, refer to the workflow files
