### ISSUE TITLE
Run the javascript file in a workflow (see yml files in .bit/workflows) and capture the output of the file (the count)

### ISSUE THREAD

**Issue by emsesc** [bitprj/counselor#29]
Example:
```yml
      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 1
        uses: cypress-io/github-action@v2
        if: ${{steps.vars.outputs.count == 38 && github.event.head_commit.message != 'Update progress'}}
        with:
          spec: cypress/integration/4.1.spec.js
```

- [ ] Run Javascript file in GitHub action and input 2 parameters: username and repo name (this can be done on the commandline)
- [ ] Store the output of the file in steps.vars.outputs.count
- [ ] Use the output (ex: 37) to determine what step should be run
